### ISSUE TITLE
Show gallons converted to liter

### ISSUE THREAD

**Issue by vesterli** [vesterli/fulcrum-wb#19]
Add a readonly field showing fuel in liters.

**Comment by sebastianbk** [comment]
Hi @vesterli. Just submitted a pull request to add readonly fields showing fuel in liters.

You can see what it looks like here: 

<img width="368" alt="image" src="https://user-images.githubusercontent.com/660576/171434627-3370d214-b0f1-4c38-9df2-9a2e28e45ad9.png">

Let me know if you'd like a different kind of styling. 🙂

**Comment by vesterli** [comment]
Implemented by @sebastianbk
